openapi: 3.1.0
info:
  title: Contacto
  contact:
    email: alvaroarriagada@currencybird.cl
  x-logo:
    url: https://currencybird.cl/img/logo_bird.png
  description: >+
    # Introducción


    Ésta API de prueba fue creada para realizar peticiones externas de empresas
    que se encuentran registradas en el sitio web de
    [CurrencyBird](https://www.currencybird.cl).

tags:
  - name: Quote
    description: Endpoint para realizar cotizaciones a través de parámetros de entrada
  - name: Reasons
    description: Endpoint para obtener el listado de razones para transferir
  - name: Payments
    description: Endpoints para ingresar un pago y consultar el estado
  - name: Beneficiaries
    description: Endpoints para consultar destinatarios asociados a una empresa
servers:
  - url: https://elb.currencybird.cl/apigateway-external/api/
  - url: https://elb.currencybird.cl/apigateway-external/api/
paths:
  /quote:
    get:
      tags:
        - Quote
      summary: Get Quote By Parameters
      description: |
        Obtener monto de destino a partir de un monto de origen
      operationId: getQuote
      parameters:
        - name: amount
          in: query
          description: Monto "ej:300000"
          schema:
            type: integer
        - name: quoteType
          in: query
          description: Tipo de cotización "sell"
          schema:
            type: string
        - name: countryCode
          in: query
          description: País de destino "ej:DE"
          schema:
            type: string
        - name: currency
          in: query
          description: Moneda de destino "ej:USD"
          schema:
            type: string
      security:
        - main_auth:
            - read:quotes
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
              example:
                status: 1
                symbol: USD
                value:
                  origin: 339
                  used: false
                exchangedRate: 884.96
        '401':
          description: Unauthorized
          $ref: '#/components/responses/Unauthorized'
  /reasons:
    get:
      tags:
        - Reasons
      summary: Get Reasons
      description: |
        Obtener el listado de razones para transferir
      operationId: getReasons
      security:
        - main_auth:
            - read:reasons
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reasons'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/Unauthorized'
  /payments:
    post:
      tags:
        - Payments
      summary: Create Payment
      description: |
        Crear un pago ingresando parámetros
      operationId: operationId
      security:
        - api_key: []
        - basic_auth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payments'
        description: requestBody description
        required: true
      responses:
        '200':
          description: OK
          headers:
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          $ref: '#/components/responses/Problem'
  /payments/{transactionCode}:
    get:
      tags:
        - Payments
      summary: Get Payment by ID
      description: |
        Obtener descripción de un pago a través de un Id
      operationId: operationId
      security:
        - api_key: []
        - basic_auth: []
      parameters:
        - name: id
          in: query
          description: id de la transferencia
          schema:
            type: integer
      responses:
        '200':
          description: OK
          headers:
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '400':
          $ref: '#/components/responses/Problem'
  /get-status-transfer: null
  /beneficiaries:
    post:
      tags:
        - Beneficiaries
      summary: Get Beneficiaries By Rut
      description: |
        Obtener la lista de destinatarios por rut de la empresa
      operationId: getBeneficiary
      parameters:
        - name: rut
          in: path
          description: Rut de la empresa
          schema:
            type: string
      security:
        - main_auth:
            - read:quotes
        - api_key: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Beneficiaries'
              example:
                id: 31598,
                name: Jim
                lastName: Morrison
                address: Manuel Rodriguez 44,
                email: jm@test.cl
                type: person,
                postalCode: 5380000,
                companyId: 64,
                countryId: 5,
                city: null,
                stateProvince: null,
                phone: 940400217,
                userId: null,
                residenceCountry: 164,
                Company.id: 64,
                Company.rut: 340878817,
                Company.name: LG,
                Company.email: lg@test.cl
                Company.createdById: 64943,
                Country.id: 2,
                Country.name: Afganistán,
                Country.currencyId: 2,
                Country.Currency.id: 2,
                Country.Currency.name: afgani,
                Country.Currency.symbol: AFN
        '401':
          description: Unauthorized
          $ref: '#/components/responses/Unauthorized'
  get:
    tags:
      - Payments
    summary: Get Payment by ID
    description: |
      Obtener descripción de un pago a través de un Id
    operationId: operationId
    security:
      - api_key: []
      - basic_auth: []
    parameters:
      - name: transactionCode
        in: query
        description: Código de la transacción
        schema:
          type: string
    responses:
      '200':
        description: OK
        headers:
          X-Expires-After:
            $ref: ../components/headers/ExpiresAfter.yaml
        content:
          application/json:
            schema:
              $ref: ../components/schemas/PaymentStatus.yaml
      '400':
        $ref: ../components/responses/Problem.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Quote:
      type: object
      properties:
        status:
          description: Estado de cotización
          type: integer
          example: 1
        symbol:
          description: Moneda
          type: string
          example: USD
        value:
          origin:
            description: Monto de destino
            type: integer
          usd:
            description: USD
            type: boolean
        exchangeRate:
          description: Tipo de cambio
          type: integer
    Unauthorized:
      type: object
      minProperties: 1
      additionalProperties: true
      description: Unauthorized
      properties:
        name:
          type: string
          description: Describe error de no autorización
          format: uri
          example: UnAuthorizedError
        message:
          type: string
          description: Unauthorized
          example: Unauthorized
        code:
          type: integer
          description: Describe el código del error
          example: 401
        type:
          type: string
          description: describe el tipo del error
          example: INVALID_TOKEN
    Reasons:
      type: object
      properties:
        id:
          description: Identificador de la actividad
          type: integer
          example: 12
        code:
          description: Codigo de actividad
          type: string
          example: 20002
        active:
          description: Estado de actividad
          type: string
          example: 1
        description:
          description: Descripción de la actividad
          type: integer
          example: Servicios de Informática
        category:
          description: Categoría de la actividad
          type: string
          example: SERVICIOS PRESTADOS
        order:
          description: Order
          type: integer
          example: 50
    Payments:
      type: object
      title: Payments
      properties:
        beneficiaryId:
          description: Identificador del destinatario
          type: integer
          example: 31757
        reason:
          description: Razón para transferir
          type: integer
          example: 55
        amount:
          description: Monto de origen en CLP
          type: integer
          example: 600000
        quoteType:
          description: Tipo de compra
          type: string
          example: buy
        currency:
          description: Moneda de destino
          type: string
          example: USD
        countryCode:
          description: País de destino de fondos
          type: string
          example: AL
        message:
          description: Mensaje de la transferencia
          type: string
          message: Fondos para estudios
    PaymentResponse:
      type: object
      title: Payments
      properties:
        id:
          description: Identificador de transferencia
          type: integer
          example: 66993
        transactionCode:
          description: Código de transferencia
          type: string
          example: 389c6c14cfb44
        status:
          description: Estado de la transferencia
          type: string
          example: new
        companyId:
          description: Identificador de la empresa
          type: integer
          example: 64
    Problem:
      type: object
      additionalProperties: true
      minProperties: 1
      description: >-
        The Problem Details JSON Object
        [[RFC7807](https://tools.ietf.org/html/rfc7807)].
      properties:
        type:
          type: string
          description: >-
            A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)]
            that identifies the problem type. It should provide human-readable
            documentation for the problem type. When this member is not present,
            its value is assumed to be "about:blank".
          format: uri
        title:
          type: string
          description: >-
            A short, human-readable summary of the problem type. It SHOULD NOT
            change from occurrence to occurrence of the problem, except for
            purposes of localization.
        status:
          type: integer
          description: The HTTP status code.
          minimum: 400
          maximum: 599
        detail:
          type: string
          description: >-
            A human-readable explanation specific to this occurrence of the
            problem.
        instance:
          type: string
          description: >-
            A URI reference that identifies the specific occurrence of the
            problem.  It may or may not yield further information if
            dereferenced.
    Payment:
      type: object
      title: get-transfer
      properties:
        id:
          description: ID de la transferencias
          type: integer
          example: 663123991
        userId:
          description: ID del usuario creador
          type: integer
          example: 64123943
        accountId:
          description: ID de la cuenta
          type: integer
          example: 999779
        amount:
          description: Monto de origen
          type: integer
          example: 300000
        mxAmount:
          description: Monto de destino
          type: integer
          example: 88123
        expectedRate:
          description: Tipo de cambio
          type: integer
          example: 827.21
        reason:
          description: Razón de la transferencia
          type: integer
          message: 55
        date:
          description: Fecha de la transferencia
          type: date
          example: '2022-03-14T20:46:59.000Z'
        transferCode:
          description: Código de a transferencia
          type: string
          example: a8e1d53291by4
        status:
          description: Estado de la transferencia
          type: string
          example: new
        type:
          description: Tipo de la transferencia
          type: integer
          example: 1
        message:
          description: Mensaje de la transferencia
          type: string
          example: Fondos para estudios en el extrajero
        companyId:
          description: Id de la empresa
          type: integer
          example: 64
        uniqueNumber:
          description: Codigo para retiro en sucrusal
          type: integer
          eample: 2084584023
    Beneficiaries:
      type: object
      properties:
        id:
          description: Identificador del destinatario
          type: integer
          example: 12
        name:
          description: Nombre del destinatario
          type: string
          example: Jim
        lastName:
          description: Apellido del destinatario
          type: string
          example: Morrison
        address:
          description: Dirección del destinatario
          type: string
          example: Avenida Louisandres 921
        email:
          description: Email del destinatario
          type: string
          example: jim@morrison.com
        type:
          description: Tipo de destinatario
          type: string
          example: person
        postalCode:
          description: Código postal
          type: integer
          example: 53000000
        companyId:
          description: Id de la empresa
          type: integer
          example: 64
        CountryId:
          description: Nacionalidad
          type: integer
          example: 2
        city:
          description: Ciudad
          type: string
          example: Aranjuez
        stateProvince:
          description: Provincia o estado
          type: string
          example: Los lagos
        phone:
          description: Teléfono
          type: integer
          example: null
        postauserId:
          description: Id del usuario creador (nulo)
          type: integer
          example: null
        residenceCountry:
          description: Id del país de destino
          type: integer
          example: 164
        Company.id:
          description: Empresa que creo
          type: integer
          example: 64
        Company.name:
          description: Nombre de empresa
          type: string
          example: LG
        Company.email:
          description: Email de la empresa
          type: string
          example: lg@test.cl
        Company.createdById:
          description: Id del usuario que lo creo
          type: integer
          example: 64943
        Country.id:
          description: País de destino
          type: integer
          example: 2
        Country.name:
          description: Nombre del país de destino
          type: string
          example: Afganistán
        Country.currencyId:
          description: Moneda país de destino
          type: integer
          example: 2
        Country.Currency.name:
          description: Moneda país de destino
          type: string
          example: afgani
        Country.Currency.symbol:
          description: Simbolo moneda de destino
          type: string
          example: AFN
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Unauthorized'
    Problem:
      description: Problem
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
  headers:
    ExpiresAfter:
      description: date in UTC when token expires
      schema:
        type: string
        format: date-time
