openapi: 3.1.0
info:
  title: Contacto
  contact:
    email: alvaroarriagada@currencybird.cl
  x-logo:
    url: 'https://currencybird.cl/img/logo_bird.png'
  description:
    $ref: ./info-description.md
tags:
  # - name: Echo
  #   description: Example echo operations.
  - name: Quote
    description: Endpoint para realizar cotizaciones a través de parámetros de entrada
    
  - name: Reasons
    description: Endpoint para obtener el listado de razones para transferir
  - name: Payments
    description: Endpoints para ingresar un pago y consultar el estado 
  # - name: Tag
  #   description: This is a tag description.
servers:

  - url: 'https://elb.currencybird.cl/apigateway-company/api/'
  - url: 'https://elb.currencybird.cl/apigateway-company/api/'
paths:
  /quote:
    $ref: paths/quote.yaml
  /reasons:
    $ref: paths/reasons.yaml
  /payment:
    $ref: paths/payment.yaml
  # '/users/{username}':
  #   $ref: 'paths/users@{username}.yaml'
  # /echo:
  #   $ref: paths/echo.yaml
  # /pathItem:
  #   $ref: paths/path-item.yaml
  # /pathItemWithExamples:
  #   $ref: paths/path-item-with-examples.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
