openapi: 3.1.0
info:
  title: Integración de aplicaciones externas
  contact:
    email: alvaroarriagada@currencybird.cl
  x-logo:
    url: 'https://currencybird.cl/img/logo_bird.png'
  description:
    $ref: ./auth.html
tags:
  - name: Quotes
    description: Endpoint para realizar cotizaciones a través de parámetros de entrada
  - name: Reasons
    description: Endpoint para obtener el listado de razones para transferir
  - name: Payments
    description: Endpoints para ingresar un pago y consultar el estado 
  - name: Beneficiaries
    description: Endpoints para consultar destinatarios asociados a una empresa

servers:

  - url: 'http://elb.currencybird.cl/apigateway-external/api/'
  - url: 'https://elb.currencybird.cl/apigateway-external/api/'
paths:
  /quotes?rut=:
    $ref: paths/quotes.yaml
  /reasons?rut=:
    $ref: paths/reasons.yaml
  /payments?rut=:
    $ref: paths/payments.yaml
  /payments/:transactionCode?rut=:
    $ref: paths/get-transfer@{transactionCode}.yaml
  /payments/:transactionCode/status?rut:
    $ref: paths/get-status-transfer@{transactionCode}.yaml
  /beneficiaries?rut=:
    $ref: paths/beneficiaries@{rut}.yaml
  /beneficiaries/:idBeneficiary/account?rut=:
    $ref: paths/getAccount@{idBeneficiary}.yaml
    
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      
