openapi: 3.1.0
info:
  title: Contacto
  contact:
    email: alvaroarriagada@currencybird.cl
  x-logo:
    url: 'https://currencybird.cl/img/logo_bird.png'
  description:
    $ref: ./info-description.md
tags:
  # - name: Echo
  #   description: Example echo operations.
  - name: Quote
    description: Endpoint para realizar cotizaciones a través de parámetros de entrada
  # - name: Tag
  #   description: This is a tag description.
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /quote:
    $ref: paths/quote.yaml
  # '/users/{username}':
  #   $ref: 'paths/users@{username}.yaml'
  # /echo:
  #   $ref: paths/echo.yaml
  # /pathItem:
  #   $ref: paths/path-item.yaml
  # /pathItemWithExamples:
  #   $ref: paths/path-item-with-examples.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
