openapi: 3.1.0
info:
  title: API para empresas
  contact:
    email: alvaroarriagada@currencybird.cl
  x-logo:
    url: 'https://currencybird.cl/img/logo_bird.png'
  description:
    $ref: ./info-description.md
tags:
  - name: Quotes
    description: Endpoint para realizar cotizaciones a través de parámetros de entrada
  - name: Reasons
    description: Endpoint para obtener el listado de razones para transferir
  - name: Payments
    description: Endpoints para ingresar un pago y consultar el estado 
  - name: Beneficiaries
    description: Endpoints para consultar destinatarios asociados a una empresa

servers:

  - url: 'http://elb.currencybird.cl/apigateway-company/api/'
  - url: 'https://elb.currencybird.cl/apigateway-company/api/'
paths:
  /quotes:
    $ref: paths/quotes.yaml
  /reasons:
    $ref: paths/reasons.yaml
  /payments:
    $ref: paths/payments.yaml
  /payments/{transactionCode}:
    $ref: paths/get-transfer@{transactionCode}.yaml
  /payments/{transactionCode}/status:
    $ref: paths/get-status-transfer@{transactionCode}.yaml
  /beneficiaries:
    $ref: paths/beneficiaries@{rut}.yaml
    
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
